name: GitHub CI
on:
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - master
  push:
    tags:        
      - release-*
      
  workflow_dispatch:
  
env:
  CI_REQ_DOTNET_SDK_VER: 6.0.x
  
jobs:
  build:
    name: Build NETReactorSlayer
    runs-on: windows-latest
    defaults:
            run:
              shell: pwsh
    strategy:
      matrix:
        platform: [
          netframework,
          net6.0-win32, net6.0-win64, net6.0-win-arm, net6.0-win-arm64,
          net6.0-linux64, net6.0-linux-arm, net6.0-linux-arm64,
          net6.0-osx64, 
        ]
        include:
          - platform: netframework
            build-dir: net48
            
            
          - platform: net6.0-win32
            build-dir: net6.0\win-x86\publish
            
          - platform: net6.0-win64
            build-dir: net6.0\win-x64\publish

          - platform: net6.0-win-arm
            build-dir: net6.0\win-arm\publish

          - platform: net6.0-win-arm64
            build-dir: net6.0\win-arm64\publish
            
          - platform: net6.0-linux64
            build-dir: net6.0\linux-x64\publish

          - platform: net6.0-linux-arm
            build-dir: net6.0\linux-arm\publish
            
          - platform: net6.0-linux-arm64
            build-dir: net6.0\linux-arm64\publish

          - platform: net6.0-osx64
            build-dir: net6.0\osx-x64\publish
          
          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            submodules: true
            
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.CI_REQ_DOTNET_SDK_VER}}
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2.0.0
        
      - name: Restore NuGet packages for NETReactorSlayer.GUI
        run: nuget restore NETReactorSlayer.GUI\NETReactorSlayer.GUI.csproj -PackagesDirectory .\packages\
        if: ${{ contains(matrix.platform, 'netframework') }}
        
      - name: Build ${{matrix.platform}}
        run: .\build.ps1 ${{matrix.platform}}
        
      - name: Create output directory
        run: New-Item -ItemType Directory -Path C:\builtfiles\NETReactorSlayer-${{matrix.platform}} -Force > $null
        continue-on-error: true
        
      - name: Copy release files for upload
        run: Copy-Item -Path bin\Release\${{matrix.build-dir}}\* -Destination C:\builtfiles\NETReactorSlayer-${{matrix.platform}} -Recurse
      
      - name: Upload NETReactorSlayer
        uses: actions/upload-artifact@v4
        if: ${{ contains(matrix.platform, 'netframework') && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')) }}
        with:
          name: NETReactorSlayer-${{matrix.platform}}-${{ github.sha }}
          path: C:\builtfiles\NETReactorSlayer-${{matrix.platform}}
          if-no-files-found: error

      - name: Upload NETReactorSlayer.CLI
        uses: actions/upload-artifact@v4
        if: ${{ !contains(matrix.platform, 'netframework') && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))}}
        with:
          name: NETReactorSlayer.CLI-${{matrix.platform}}-${{ github.sha }}
          path: C:\builtfiles\NETReactorSlayer-${{matrix.platform}}
          if-no-files-found: error

      - name: Create release archive
        if: startsWith(github.ref, 'refs/tags/')
        run: Compress-Archive -Path "C:\builtfiles\NETReactorSlayer-${{matrix.platform}}" -CompressionLevel 'Optimal' -DestinationPath "C:\builtfiles\NETReactorSlayer-${{matrix.platform}}.zip" -Force

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: "C:\builtfiles\NETReactorSlayer-${{matrix.platform}}.zip"
