name: GitHub CI
on:
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - master
  push:
    tags:        
      - release-*
      
  workflow_dispatch:
  
env:
  CI_REQ_DOTNET_SDK_VER: 8.0.x
  
jobs:
  build:
    name: Build NETReactorSlayer
    runs-on: windows-latest
    defaults:
            run:
              shell: pwsh
    strategy:
      fail-fast: false
      matrix:
        platform: [
          netframework,
          win-x86, win-x64, win-arm64,
          linux-x64, linux-arm, linux-arm64,
          osx-x64, 
        ]
          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
            
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.CI_REQ_DOTNET_SDK_VER}}
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2.0.0
        
      - name: Restore NuGet packages for NETReactorSlayer.GUI
        if: ${{ contains(matrix.platform, 'netframework') }}
        run: nuget restore NETReactorSlayer.GUI\NETReactorSlayer.GUI.csproj -PackagesDirectory .\packages\
        
      - name: Build ${{matrix.platform}}
        run: .\build.ps1 ${{matrix.platform}} no-msbuild
        
      - name: Create build artifacts archive
        run: Compress-Archive -Path ".\bin\Release\${{matrix.platform}}\" -CompressionLevel 'Optimal' -DestinationPath ".\bin\NETReactorSlayer-${{matrix.platform}}.zip" -Force

      - name: Upload build artifacts archive
        uses: actions/upload-artifact@v4
        with:
          name: NETReactorSlayer-${{matrix.platform}}-${{ github.sha }}
          path: "bin/NETReactorSlayer-${{matrix.platform}}.zip"
          retention-days: 1
          compression-level: 9
          if-no-files-found: error

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: "bin/NETReactorSlayer-${{matrix.platform}}.zip"
